# Site settings
title: Kopi Tubruk
email: bill.davidson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Free Java
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kopitubruk.org" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  billdavidson

# Build settings
markdown: kramdown

highlighter: pygments
