# Site settings
title: Kopi Tubruk
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Kopi tubruk means instant coffee.  This my free Java stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kopitubruk.org" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  billdavidson

# Build settings
markdown: kramdown

highlighter: pygments
